packages:
  - 'frontend/web'
  - 'frontend/mobile'
  - 'backend'


onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - better-sqlite3
  - sharp
  - sqlite3
  - unrs-resolver

overrides:
  '@types/react': '^19.0.0'
  '@types/react-dom': '^19.0.0'
  'next-intl': '4.13.0'
  'use-intl': '4.13.0'
  'icu-minify': '4.13.0'
  'next-intl-swc-plugin-extractor': '4.13.0'
  '@eloqnt/format-json': '0.0.2'
  '@eloqnt/format-po': '0.0.2'
