import * as fs from 'fs';
import * as path from 'path';

interface TokenDef {
  wordOrder: number;
  surfaceText: string;
  consonantsOnly: string;
  transliteration: string;
  strongCode: string;
  morphologyCode: string;
  gloss: string;
}

interface VerseTokens {
  chapter: number;
  verseNumber: number;
  tokens: TokenDef[];
}

interface LexiconEntryDef {
  strongCode: string;
  language: string;
  lemma: string;
  transliteration: string;
  ipa?: string;
  partOfSpeech: string;
  shortDefinition: string;
  extendedDefinition: string;
}

// 1. Catálogo exhaustivo de los 31 versículos de Génesis 1
const GENESIS_1_VERSES: {
  verse: number;
  rawHebrew: string;
  tokens: [string, string, string, string, string, string][];
}[] = [
  {
    verse: 1,
    rawHebrew:
      'בְּרֵאשִׁ֖ית בָּרָ֣א אֱלֹהִ֑ים אֵ֥ת הַשָּׁמַ֖יִם וְאֵ֥ת הָאָֽרֶץ׃',
    tokens: [
      [
        'בְּרֵאשִׁ֖ית',
        'בראשית',
        'bərē’šîṯ',
        'H7225',
        'HR/Ncfsa',
        'En el principio',
      ],
      ['בָּרָ֣א', 'ברא', 'bārā’', 'H1254', 'HVqp3ms', 'creó'],
      ['אֱלֹהִ֑ים', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios'],
      ['אֵ֥ת', 'את', '’ēṯ', 'H853', 'HTo', '[objeto directo]'],
      [
        'הַשָּׁמַ֖יִם',
        'השמים',
        'haššāmayim',
        'H8064',
        'HTd/Ncmpa',
        'los cielos',
      ],
      ['וְאֵ֥ת', 'ואת', 'wə’ēṯ', 'H853', 'HC/To', 'y [objeto]'],
      ['הָאָֽרֶץ׃', 'הארץ', 'hā’āreṣ', 'H776', 'HTd/Ncfsa', 'la tierra.'],
    ],
  },
  {
    verse: 2,
    rawHebrew:
      'וְהָאָ֗רֶץ הָיְתָ֥ה תֹ֙הוּ֙ וָבֹ֔הוּ וְחֹ֖שֶׁךְ עַל־פְּנֵ֣י תְה֑וֹם וְר֣וּחַ אֱלֹהִ֔ים מְרַחֶ֖פֶת עַל־פְּנֵ֥י הַמָּֽיִם׃',
    tokens: [
      [
        'וְהָאָ֗רֶץ',
        'והארץ',
        'wəhā’āreṣ',
        'H776',
        'HC/Td/Ncfsa',
        'Y la tierra',
      ],
      ['הָיְתָ֥ה', 'היתה', 'hāyəṯâ', 'H1961', 'HVqp3fs', 'estaba'],
      ['תֹ֙הוּ֙', 'תהו', 'ṯōhû', 'H8414', 'HNcmsa', 'sin forma'],
      ['וָבֹ֔הוּ', 'ובהו', 'wāḇōhû', 'H922', 'HC/Ncmsa', 'y vacía,'],
      [
        'וְחֹ֖שֶׁךְ',
        'וחשך',
        'wəḥōšeḵ',
        'H2822',
        'HC/Ncmsa',
        'y las tinieblas [estaban]',
      ],
      [
        'עַל־פְּנֵ֣י',
        'על־פני',
        '‘al-pənê',
        'H6440',
        'HR/Ncbpc',
        'sobre la faz de',
      ],
      ['תְה֑וֹם', 'תהום', 'ṯəhôm', 'H8415', 'HNcfsa', 'el abismo,'],
      ['וְר֣וּחַ', 'ורוח', 'wərûaḥ', 'H7307', 'HC/Ncbsc', 'y el Espíritu de'],
      ['אֱלֹהִ֔ים', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios'],
      [
        'מְרַחֶ֖פֶת',
        'מרחפת',
        'məraḥep̱eṯ',
        'H7363',
        'HVprmfsa',
        'se movía / aleteaba',
      ],
      [
        'עַל־פְּנֵ֥י',
        'על־פני',
        '‘al-pənê',
        'H6440',
        'HR/Ncbpc',
        'sobre la faz de',
      ],
      ['הַמָּֽיִם׃', 'המים', 'hammāyim', 'H4325', 'HTd/Ncmpa', 'las aguas.'],
    ],
  },
  {
    verse: 3,
    rawHebrew: 'וַיֹּ֥אמֶר אֱלֹהִ֖ים יְהִ֣י א֑וֹר וַֽיְהִי־אֽוֹר׃',
    tokens: [
      ['וַיֹּ֥אמֶר', 'ויאמר', 'wayyō’mer', 'H559', 'HC/Vqw3ms', 'Y dijo'],
      ['אֱלֹהִ֖ים', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios:'],
      ['יְהִ֣י', 'יהי', 'yəhî', 'H1961', 'HVqj3ms', 'Sea / Haya'],
      ['א֑וֹר', 'אור', '’ôr', 'H216', 'HNcmsa', 'luz;'],
      [
        'וַֽיְהִי־אֽוֹר׃',
        'ויהי־אור',
        'wayhî-’ôr',
        'H216',
        'HC/Vqw3ms-Ncmsa',
        'y fue la luz.',
      ],
    ],
  },
  {
    verse: 4,
    rawHebrew:
      'וַיַּ֧רְא אֱלֹהִ֛ים אֶת־הָא֖וֹר כִּי־ט֑וֹב וַיַּבְדֵּ֣ל אֱלֹהִ֔ים בֵּ֥ין הָא֖וֹר וּבֵ֥ין הַחֹֽשֶׁךְ׃',
    tokens: [
      ['וַיַּ֧רְא', 'וירא', 'wayyar’', 'H7200', 'HC/Vqw3ms', 'Y vio'],
      ['אֱלֹהִ֛ים', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios'],
      ['אֶת־הָא֖וֹר', 'את־האור', '’eṯ-hā’ôr', 'H216', 'HTo/Td/Ncmsa', 'la luz'],
      ['כִּי־ט֑וֹב', 'כי־טוב', 'kî-ṭôḇ', 'H2896', 'HC/Aamsa', 'que era buena;'],
      ['וַיַּבְדֵּ֣ל', 'ויבדל', 'wayyaḇdēl', 'H914', 'HC/Vhw3ms', 'y separó'],
      ['אֱלֹהִ֔ים', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios'],
      ['בֵּ֥ין', 'בין', 'bên', 'H996', 'HR', 'entre'],
      ['הָא֖וֹר', 'האור', 'hā’ôr', 'H216', 'HTd/Ncmsa', 'la luz'],
      ['וּבֵ֥ין', 'ובין', 'ûḇên', 'H996', 'HC/R', 'y entre'],
      [
        'הַחֹֽשֶׁךְ׃',
        'החשך',
        'haḥōšeḵ',
        'H2822',
        'HTd/Ncmsa',
        'las tinieblas.',
      ],
    ],
  },
  {
    verse: 5,
    rawHebrew:
      'וַיִּקְרָ֨א אֱלֹהִ֤ים ׀ לָאוֹר֙ י֔וֹם וְלַחֹ֖שֶׁךְ קָ֣רָא לָ֑יְלָה וַֽיְהִי־עֶ֥רֶב וַֽיְהִי־בֹ֖קֶר י֥וֹם אֶחָֽד׃',
    tokens: [
      ['וַיִּקְרָ֨א', 'ויקרא', 'wayyiqrā’', 'H7121', 'HC/Vqw3ms', 'Y llamó'],
      ['אֱלֹהִ֤ים', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios'],
      ['לָאוֹר֙', 'לאור', 'lā’ôr', 'H216', 'HRd/Ncmsa', 'a la luz'],
      ['י֔וֹם', 'יום', 'yôm', 'H3117', 'HNcmsa', 'Día,'],
      [
        'וְלַחֹ֖שֶׁךְ',
        'ולחשך',
        'wəlaḥōšeḵ',
        'H2822',
        'HC/Rd/Ncmsa',
        'y a las tinieblas',
      ],
      ['קָ֣רָא', 'קרא', 'qārā’', 'H7121', 'HVqp3ms', 'llamó'],
      ['לָ֑יְלָה', 'לילה', 'lāyəlâ', 'H3915', 'HNcmsa', 'Noche.'],
      [
        'וַֽיְהִי־עֶ֥רֶב',
        'ויהי־ערב',
        'wayhî-‘ereḇ',
        'H6153',
        'HC/Vqw3ms-Ncmsa',
        'Y fue la tarde',
      ],
      [
        'וַֽיְהִי־בֹ֖קֶר',
        'ויהי־בקר',
        'wayhî-ḇōqer',
        'H1242',
        'HC/Vqw3ms-Ncmsa',
        'y fue la mañana',
      ],
      [
        'י֥וֹם אֶחָֽד׃',
        'יום אחד',
        'yôm ’eḥāḏ',
        'H259',
        'HNcmsa/Acmsa',
        'un día (día primero).',
      ],
    ],
  },
  {
    verse: 6,
    rawHebrew:
      'וַיֹּ֣אמֶר אֱלֹהִ֔ים יְהִ֥י רָקִ֖יעַ בְּת֣וֹךְ הַמָּ֑יִם וִיהִ֣י מַבְדִּ֔יל בֵּ֥ין מַ֖יִם לָמָֽיִם׃',
    tokens: [
      ['וַיֹּ֣אמֶר', 'ויאמר', 'wayyō’mer', 'H559', 'HC/Vqw3ms', 'Y dijo'],
      ['אֱלֹהִ֔ים', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios:'],
      ['יְהִ֥י', 'יהי', 'yəhî', 'H1961', 'HVqj3ms', 'Haya'],
      [
        'רָקִ֖יעַ',
        'רקיע',
        'rāqîa‘',
        'H7549',
        'HNcmsa',
        'expansión / firmamento',
      ],
      ['בְּת֣וֹךְ', 'בתוך', 'bəṯôḵ', 'H8432', 'HR/Ncmsc', 'en medio de'],
      ['הַמָּ֑יִם', 'המים', 'hammāyim', 'H4325', 'HTd/Ncmpa', 'las aguas,'],
      ['וִיהִ֣י', 'ויהי', 'wîhî', 'H1961', 'HC/Vqj3ms', 'y sea'],
      ['מַבְדִּ֔יל', 'מבדיל', 'maḇdîl', 'H914', 'HVhrmsa', 'separación'],
      ['בֵּ֥ין', 'בין', 'bên', 'H996', 'HR', 'entre'],
      ['מַ֖יִם', 'מים', 'mayim', 'H4325', 'HNcmpa', 'aguas'],
      ['לָמָֽיִם׃', 'למים', 'lāmāyim', 'H4325', 'HRd/Ncmpa', 'de aguas.'],
    ],
  },
  {
    verse: 7,
    rawHebrew:
      'וַיַּ֣עַשׂ אֱלֹהִים֮ אֶת־הָרָקִיעַ֒ וַיַּבְדֵּ֗ל בֵּ֤ין הַמַּ֙יִם֙ אֲשֶׁר֙ מִתַּ֣חַת לָרָקִ֔יעַ וּבֵ֣ין הַמַּ֔יִם אֲשֶׁ֖ר מֵעַ֣ל לָרָקִ֑יעַ וַֽיְהִי־כֵֽן׃',
    tokens: [
      ['וַיַּ֣עַשׂ', 'ויעש', 'wayya‘aś', 'H6213', 'HC/Vqw3ms', 'E hizo'],
      ['אֱלֹהִים֮', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios'],
      [
        'אֶת־הָרָקִיעַ֒',
        'את־הרקיע',
        '’eṯ-hārāqîa‘',
        'H7549',
        'HTo/Td/Ncmsa',
        'la expansión,',
      ],
      ['וַיַּבְדֵּ֗ל', 'ויבדל', 'wayyaḇdēl', 'H914', 'HC/Vhw3ms', 'y separó'],
      ['בֵּ֤ין', 'בין', 'bên', 'H996', 'HR', 'entre'],
      ['הַמַּ֙יִם֙', 'המים', 'hammayim', 'H4325', 'HTd/Ncmpa', 'las aguas'],
      ['אֲשֶׁר֙', 'אשר', '’ăšer', 'H834', 'HTr', 'que [estaban]'],
      ['מִתַּ֣חַת', 'מתחת', 'mittaḥaṯ', 'H8478', 'HR/R', 'debajo de'],
      [
        'לָרָקִ֔יעַ',
        'לרקיע',
        'lārāqîa‘',
        'H7549',
        'HRd/Ncmsa',
        'la expansión,',
      ],
      ['וּבֵ֣ין', 'ובין', 'ûḇên', 'H996', 'HC/R', 'y entre'],
      ['הַמַּ֔יִם', 'המים', 'hammayim', 'H4325', 'HTd/Ncmpa', 'las aguas'],
      ['אֲשֶׁ֖ר', 'אשר', '’ăšer', 'H834', 'HTr', 'que [estaban]'],
      ['מֵעַ֣ל', 'מעל', 'mē‘al', 'H5921', 'HR/R', 'sobre'],
      [
        'לָרָקִ֑יעַ',
        'לרקיע',
        'lārāqîa‘',
        'H7549',
        'HRd/Ncmsa',
        'la expansión.',
      ],
      [
        'וַֽיְהִי־כֵֽן׃',
        'ויהי־כן',
        'wayhî-ḵēn',
        'H3651',
        'HC/Vqw3ms-D',
        'Y fue así.',
      ],
    ],
  },
  {
    verse: 8,
    rawHebrew:
      'וַיִּקְרָ֧א אֱלֹהִ֛ים לָֽרָקִ֖יעַ שָׁמָ֑יִם וַֽיְהִי־עֶ֥רֶב וַֽיְהִי־בֹ֖קֶר י֥וֹם שֵׁנִֽי׃',
    tokens: [
      ['וַיִּקְרָ֧א', 'ויקרא', 'wayyiqrā’', 'H7121', 'HC/Vqw3ms', 'Y llamó'],
      ['אֱלֹהִ֛ים', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios'],
      [
        'לָֽרָקִ֖יעַ',
        'לרקיע',
        'lārāqîa‘',
        'H7549',
        'HRd/Ncmsa',
        'a la expansión',
      ],
      ['שָׁמָ֑יִם', 'שמים', 'šāmāyim', 'H8064', 'HNcmpa', 'Cielos.'],
      [
        'וַֽיְהִי־עֶ֥רֶב',
        'ויהי־ערב',
        'wayhî-‘ereḇ',
        'H6153',
        'HC/Vqw3ms-Ncmsa',
        'Y fue la tarde',
      ],
      [
        'וַֽיְהִי־בֹ֖קֶר',
        'ויהי־בקר',
        'wayhî-ḇōqer',
        'H1242',
        'HC/Vqw3ms-Ncmsa',
        'y fue la mañana',
      ],
      [
        'י֥וֹם שֵׁנִֽי׃',
        'יום שני',
        'yôm šēnî',
        'H8145',
        'HNcmsa/Aomsa',
        'el día segundo.',
      ],
    ],
  },
  {
    verse: 9,
    rawHebrew:
      'וַיֹּ֣אמֶר אֱלֹהִ֗ים יִקָּו֨וּ הַמַּ֜יִם מִתַּ֤חַת הַשָּׁמַ֙יִם֙ אֶל־מָק֣וֹם אֶחָ֔ד וְתֵרָאֶ֖ה הַיַּבָּשָׁ֑ה וַֽיְהִי־כֵֽן׃',
    tokens: [
      ['וַיֹּ֣אמֶר', 'ויאמר', 'wayyō’mer', 'H559', 'HC/Vqw3ms', 'Y dijo'],
      ['אֱלֹהִ֗ים', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios:'],
      ['יִקָּו֨וּ', 'יקוו', 'yiqqāwû', 'H6960', 'HVNi3mp', 'Júntense'],
      ['הַמַּ֜יִם', 'המים', 'hammayim', 'H4325', 'HTd/Ncmpa', 'las aguas'],
      ['מִתַּ֤חַת', 'מתחת', 'mittaḥaṯ', 'H8478', 'HR/R', 'debajo de'],
      [
        'הַשָּׁמַ֙יִם֙',
        'השמים',
        'haššāmayim',
        'H8064',
        'HTd/Ncmpa',
        'los cielos',
      ],
      [
        'אֶל־מָק֣וֹם',
        'אל־מקום',
        '’el-māqôm',
        'H4725',
        'HR/Ncmsa',
        'en un lugar',
      ],
      ['אֶחָ֔ד', 'אחד', '’eḥāḏ', 'H259', 'HAcmsa', 'uno / solo,'],
      [
        'וְתֵרָאֶ֖ה',
        'ותראה',
        'wəṯērā’eh',
        'H7200',
        'HC/VNi3fs',
        'y descúbrase / aparezca',
      ],
      [
        'הַיַּבָּשָׁ֑ה',
        'היבשה',
        'hayyabbāšâ',
        'H3004',
        'HTd/Ncfsa',
        'lo seco / la tierra seca.',
      ],
      [
        'וַֽיְהִי־כֵֽן׃',
        'ויהי־כן',
        'wayhî-ḵēn',
        'H3651',
        'HC/Vqw3ms-D',
        'Y fue así.',
      ],
    ],
  },
  {
    verse: 10,
    rawHebrew:
      'וַיִּקְרָ֨א אֱלֹהִ֤ים ׀ לַיַּבָּשָׁה֙ אֶ֔רֶץ וּלְמִקְוֵ֥ה הַמַּ֖יִם קָרָ֣א יַמִּ֑ים וַיַּ֥רְא אֱלֹהִ֖ים כִּי־טֽוֹב׃',
    tokens: [
      ['וַיִּקְרָ֨א', 'ויקרא', 'wayyiqrā’', 'H7121', 'HC/Vqw3ms', 'Y llamó'],
      ['אֱלֹהִ֤ים', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios'],
      [
        'לַיַּבָּשָׁה֙',
        'ליבשה',
        'layyabbāšâ',
        'H3004',
        'HRd/Ncfsa',
        'a lo seco',
      ],
      ['אֶ֔רֶץ', 'ארץ', '’ereṣ', 'H776', 'HNcfsa', 'Tierra,'],
      [
        'וּלְמִקְוֵ֥ה',
        'ולמקוה',
        'ûləmiqwēh',
        'H4723',
        'HC/Rd/Ncmsc',
        'y a la reunión de',
      ],
      ['הַמַּ֖יִם', 'המים', 'hammayim', 'H4325', 'HTd/Ncmpa', 'las aguas'],
      ['קָרָ֣א', 'קרא', 'qārā’', 'H7121', 'HVqp3ms', 'llamó'],
      ['יַמִּ֑ים', 'ימים', 'yammîm', 'H3220', 'HNcmpa', 'Mares.'],
      ['וַיַּ֥רְא', 'וירא', 'wayyar’', 'H7200', 'HC/Vqw3ms', 'Y vio'],
      ['אֱלֹהִ֖ים', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios'],
      [
        'כִּי־טֽוֹב׃',
        'כי־טוב',
        'kî-ṭôḇ',
        'H2896',
        'HC/Aamsa',
        'que era bueno.',
      ],
    ],
  },
  {
    verse: 11,
    rawHebrew:
      'וַיֹּ֣אמֶר אֱלֹהִ֗ים תַּֽדְשֵׁ֤א הָאָ֙רֶץ֙ דֶּ֔שֶׁא עֵ֚שֶׂב מַזְרִ֣יעַ זֶ֔רַע עֵ֣ץ פְּרִ֞י עֹ֤שֶׂה פְּרִי֙ לְמִינ֔וֹ אֲשֶׁ֥ר זַרְעוֹ־ב֖וֹ עַל־הָאָ֑רֶץ וַֽיְהִי־כֵֽן׃',
    tokens: [
      ['וַיֹּ֣אמֶר', 'ויאמר', 'wayyō’mer', 'H559', 'HC/Vqw3ms', 'Y dijo'],
      ['אֱלֹהִ֗ים', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios:'],
      ['תַּֽדְשֵׁ֤א', 'תדשא', 'taḏšē’', 'H1876', 'HVhj3fs', 'Produzca / Brote'],
      ['הָאָ֙רֶץ֙', 'הארץ', 'hā’āreṣ', 'H776', 'HTd/Ncfsa', 'la tierra'],
      ['דֶּ֔שֶׁא', 'דשא', 'deše’', 'H1877', 'HNcmsa', 'hierba verde,'],
      ['עֵ֚שֶׂב', 'עשב', '‘ēśeḇ', 'H6212', 'HNcmsa', 'hierba que'],
      ['מַזְרִ֣יעַ', 'מזריע', 'mazrîa‘', 'H2232', 'HVhrmsa', 'dé / produzca'],
      ['זֶ֔רַע', 'זרע', 'zera‘', 'H2233', 'HNcmsa', 'semilla;'],
      ['עֵ֣ץ', 'עץ', '‘ēṣ', 'H6086', 'HNcmsc', 'árbol'],
      ['פְּרִ֞י', 'פרי', 'pərî', 'H6529', 'HNcmsa', 'de fruto'],
      ['עֹ֤שֶׂה', 'עשה', '‘ōśeh', 'H6213', 'HVqrmsa', 'que dé'],
      ['פְּרִי֙', 'פרי', 'pərî', 'H6529', 'HNcmsa', 'fruto'],
      [
        'לְמִינ֔וֹ',
        'למינו',
        'ləmînô',
        'H4327',
        'HR/Ncmsc/Sp3ms',
        'según su género / especie,',
      ],
      ['אֲשֶׁ֥ר', 'אשר', '’ăšer', 'H834', 'HTr', 'cuya'],
      [
        'זַרְעוֹ־ב֖וֹ',
        'זרעו־בו',
        'zar‘ô-ḇô',
        'H2233',
        'HNcmsc/Sp3ms-R/Sp3ms',
        'semilla esté en él',
      ],
      [
        'עַל־הָאָ֑רֶץ',
        'על־הארץ',
        '‘al-hā’āreṣ',
        'H776',
        'HR/Td/Ncfsa',
        'sobre la tierra.',
      ],
      [
        'וַֽיְהִי־כֵֽן׃',
        'ויהי־כן',
        'wayhî-ḵēn',
        'H3651',
        'HC/Vqw3ms-D',
        'Y fue así.',
      ],
    ],
  },
  {
    verse: 12,
    rawHebrew:
      'וַתּוֹצֵ֨א הָאָ֜רֶץ דֶּ֠שֶׁא עֵ֣שֶׂב מַזְרִ֤יעַ זֶ֙רַע֙ לְמִינֵ֔הוּ וְעֵ֧ץ עֹֽשֶׂה־פְּרִ֛י אֲשֶׁ֥ר זַרְעוֹ־ב֖וֹ לְמִינֵ֑הוּ וַיַּ֥רְא אֱלֹהִ֖ים כִּי־טֽוֹב׃',
    tokens: [
      ['וַתּוֹצֵ֨א', 'ותוצא', 'wattôṣē’', 'H3318', 'HC/Vhw3fs', 'Y produjo'],
      ['הָאָ֜רֶץ', 'הארץ', 'hā’āreṣ', 'H776', 'HTd/Ncfsa', 'la tierra'],
      ['דֶּ֠שֶׁא', 'דשא', 'deše’', 'H1877', 'HNcmsa', 'hierba verde,'],
      ['עֵ֣שֶׂב', 'עשב', '‘ēśeḇ', 'H6212', 'HNcmsa', 'hierba que'],
      ['מַזְרִ֤יעַ', 'מזריע', 'mazrîa‘', 'H2232', 'HVhrmsa', 'da'],
      ['זֶ֙רַע֙', 'זרע', 'zera‘', 'H2233', 'HNcmsa', 'semilla'],
      [
        'לְמִינֵ֔הוּ',
        'למינהו',
        'ləmînēhû',
        'H4327',
        'HR/Ncmsc/Sp3ms',
        'según su especie,',
      ],
      ['וְעֵ֧ץ', 'ועץ', 'wə‘ēṣ', 'H6086', 'HC/Ncmsc', 'y árbol'],
      [
        'עֹֽשֶׂה־פְּרִ֛י',
        'עשה־פרי',
        '‘ōśeh-pərî',
        'H6529',
        'HVqrmsa-Ncmsa',
        'que da fruto,',
      ],
      ['אֲשֶׁ֥ר', 'אשר', '’ăšer', 'H834', 'HTr', 'cuya'],
      [
        'זַרְעוֹ־ב֖וֹ',
        'זרעו־בו',
        'zar‘ô-ḇô',
        'H2233',
        'HNcmsc/Sp3ms-R/Sp3ms',
        'semilla está en él',
      ],
      [
        'לְמִינֵ֑הוּ',
        'למינהו',
        'ləmînēhû',
        'H4327',
        'HR/Ncmsc/Sp3ms',
        'según su especie.',
      ],
      ['וַיַּ֥רְא', 'וירא', 'wayyar’', 'H7200', 'HC/Vqw3ms', 'Y vio'],
      ['אֱלֹהִ֖ים', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios'],
      [
        'כִּי־טֽוֹב׃',
        'כי־טוב',
        'kî-ṭôḇ',
        'H2896',
        'HC/Aamsa',
        'que era bueno.',
      ],
    ],
  },
  {
    verse: 13,
    rawHebrew: 'וַֽיְהִי־עֶ֥רֶב וַֽיְהִי־בֹ֖קֶר י֥וֹם שְׁלִישִֽׁי׃',
    tokens: [
      [
        'וַֽיְהִי־עֶ֥רֶב',
        'ויהי־ערב',
        'wayhî-‘ereḇ',
        'H6153',
        'HC/Vqw3ms-Ncmsa',
        'Y fue la tarde',
      ],
      [
        'וַֽיְהִי־בֹ֖קֶר',
        'ויהי־בקר',
        'wayhî-ḇōqer',
        'H1242',
        'HC/Vqw3ms-Ncmsa',
        'y fue la mañana',
      ],
      [
        'י֥וֹם שְׁלִישִֽׁי׃',
        'יום שלישי',
        'yôm šəlîšî',
        'H7992',
        'HNcmsa/Aomsa',
        'el día tercero.',
      ],
    ],
  },
  {
    verse: 14,
    rawHebrew:
      'וַיֹּ֣אמֶר אֱלֹהִ֗ים יְהִ֤י מְאֹרֹת֙ בִּרְקִ֣יעַ הַשָּׁמַ֔יִם לְהַבְדִּ֕יל בֵּ֥ין הַיּ֖וֹם וּבֵ֣ין הַלָּ֑יְלָה וְהָי֤וּ לְאֹתֹת֙ וּלְמ֣וֹעֲדִ֔ים וּלְיָמִ֖ים וְשָׁנִֽים׃',
    tokens: [
      ['וַיֹּ֣אמֶר', 'ויאמר', 'wayyō’mer', 'H559', 'HC/Vqw3ms', 'Y dijo'],
      ['אֱלֹהִ֗ים', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios:'],
      ['יְהִ֤י', 'יהי', 'yəhî', 'H1961', 'HVqj3ms', 'Haya'],
      ['מְאֹרֹת֙', 'מארת', 'mə’ōrōṯ', 'H3974', 'HNcfpa', 'lumbreras'],
      [
        'בִּרְקִ֣יעַ',
        'ברקיע',
        'birqîa‘',
        'H7549',
        'HR/Ncmsc',
        'en la expansión de',
      ],
      [
        'הַשָּׁמַ֔יִם',
        'השמים',
        'haššāmayim',
        'H8064',
        'HTd/Ncmpa',
        'los cielos',
      ],
      ['לְהַבְדִּ֕יל', 'להבדיל', 'ləhaḇdîl', 'H914', 'HR/Vhc', 'para separar'],
      ['בֵּ֥ין', 'בין', 'bên', 'H996', 'HR', 'entre'],
      ['הַיּ֖וֹם', 'היום', 'hayyôm', 'H3117', 'HTd/Ncmsa', 'el día'],
      ['וּבֵ֣ין', 'ובין', 'ûḇên', 'H996', 'HC/R', 'y entre'],
      ['הַלָּ֑יְלָה', 'הלילה', 'hallayəlâ', 'H3915', 'HTd/Ncmsa', 'la noche;'],
      ['וְהָי֤וּ', 'והיו', 'wəhāyû', 'H1961', 'HC/Vqq3cp', 'y sirvan'],
      ['לְאֹתֹת֙', 'לאתת', 'lə’ōṯōṯ', 'H226', 'HR/Ncfpa', 'de señales'],
      [
        'וּלְמ֣וֹעֲדִ֔ים',
        'ולמועדים',
        'ûləmô‘ăḏîm',
        'H4150',
        'HC/R/Ncmpa',
        'y para estaciones / fiestas,',
      ],
      ['וּלְיָמִ֖ים', 'ולימים', 'ûləyāmîm', 'H3117', 'HC/R/Ncmpa', 'para días'],
      ['וְשָׁנִֽים׃', 'ושנים', 'wəšānîm', 'H8141', 'HC/Ncfpa', 'y años.'],
    ],
  },
  {
    verse: 15,
    rawHebrew:
      'וְהָי֤וּ לִמְאוֹרֹת֙ בִּרְקִ֣יעַ הַשָּׁמַ֔יִם לְהָאִ֖יר עַל־הָאָ֑רֶץ וַֽיְהִי־כֵֽן׃',
    tokens: [
      ['וְהָי֤וּ', 'והיו', 'wəhāyû', 'H1961', 'HC/Vqq3cp', 'Y sean'],
      [
        'לִמְאוֹרֹת֙',
        'למאורת',
        'lim’ôrōṯ',
        'H3974',
        'HR/Ncfpa',
        'por lumbreras',
      ],
      [
        'בִּרְקִ֣יעַ',
        'ברקיע',
        'birqîa‘',
        'H7549',
        'HR/Ncmsc',
        'en la expansión de',
      ],
      [
        'הַשָּׁמַ֔יִם',
        'השמים',
        'haššāmayim',
        'H8064',
        'HTd/Ncmpa',
        'los cielos',
      ],
      ['לְהָאִ֖יר', 'להאיר', 'ləhā’îr', 'H215', 'HR/Vhc', 'para alumbrar'],
      [
        'עַל־הָאָ֑רֶץ',
        'על־הארץ',
        '‘al-hā’āreṣ',
        'H776',
        'HR/Td/Ncfsa',
        'sobre la tierra.',
      ],
      [
        'וַֽיְהִי־כֵֽן׃',
        'ויהי־כן',
        'wayhî-ḵēn',
        'H3651',
        'HC/Vqw3ms-D',
        'Y fue así.',
      ],
    ],
  },
  {
    verse: 16,
    rawHebrew:
      'וַיַּ֣עַשׂ אֱלֹהִ֔ים אֶת־שְׁנֵ֥י הַמְּאֹרֹ֖ת הַגְּדֹלִ֑ים אֶת־הַמָּא֤וֹר הַגָּדֹל֙ לְמֶמְשֶׁ֣לֶת הַיּ֔וֹם וְאֶת־הַמָּא֤וֹר הַקָּטֹן֙ לְמֶמְשֶׁ֣לֶת הַלַּ֔יְלָה וְאֵ֖ת הַכּוֹכָבִֽים׃',
    tokens: [
      ['וַיַּ֣עַשׂ', 'ויעש', 'wayya‘aś', 'H6213', 'HC/Vqw3ms', 'E hizo'],
      ['אֱלֹהִ֔ים', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios'],
      ['אֶת־שְׁנֵ֥י', 'את־שני', '’eṯ-šənê', 'H8147', 'HTo/Acmdc', 'las dos'],
      ['הַמְּאֹרֹ֖ת', 'המארת', 'hammə’ōrōṯ', 'H3974', 'HTd/Ncfpa', 'lumbreras'],
      [
        'הַגְּדֹלִ֑ים',
        'הגדלים',
        'haggəḏōlîm',
        'H1419',
        'HTd/Aampa',
        'grandes:',
      ],
      [
        'אֶת־הַמָּא֤וֹר',
        'את־המאור',
        '’eṯ-hammā’ôr',
        'H3974',
        'HTo/Td/Ncmsa',
        'la lumbrera',
      ],
      ['הַגָּדֹל֙', 'הגדל', 'haggāḏōl', 'H1419', 'HTd/Aamsa', 'mayor'],
      [
        'לְמֶמְשֶׁ֣לֶת',
        'לממשלת',
        'ləmemšeleṯ',
        'H4475',
        'HR/Ncfsc',
        'para señorear en',
      ],
      ['הַיּ֔וֹם', 'היום', 'hayyôm', 'H3117', 'HTd/Ncmsa', 'el día,'],
      [
        'וְאֶת־הַמָּא֤וֹר',
        'ואת־המאור',
        'wə’eṯ-hammā’ôr',
        'H3974',
        'HC/To/Td/Ncmsa',
        'y la lumbrera',
      ],
      ['הַקָּטֹן֙', 'הקטן', 'haqqāṭōn', 'H6996', 'HTd/Aamsa', 'menor'],
      [
        'לְמֶמְשֶׁ֣לֶת',
        'לממשלת',
        'ləmemšeleṯ',
        'H4475',
        'HR/Ncfsc',
        'para señorear en',
      ],
      ['הַלַּ֔יְלָה', 'הלילה', 'hallayəlâ', 'H3915', 'HTd/Ncmsa', 'la noche;'],
      ['וְאֵ֖ת', 'ואת', 'wə’ēṯ', 'H853', 'HC/To', 'hizo también'],
      [
        'הַכּוֹכָבִֽים׃',
        'הכוכבים',
        'hakkôḵāḇîm',
        'H3556',
        'HTd/Ncmpa',
        'las estrellas.',
      ],
    ],
  },
  {
    verse: 17,
    rawHebrew:
      'וַיִּתֵּ֥ן אֹתָ֛ם אֱלֹהִ֖ים בִּרְקִ֣יעַ הַשָּׁמָ֑יִם לְהָאִ֖יר עַל־הָאָֽרֶץ׃',
    tokens: [
      ['וַיִּתֵּ֥ן', 'ויתן', 'wayyittēn', 'H5414', 'HC/Vqw3ms', 'Y las puso'],
      ['אֹתָ֛ם', 'אתם', '’ōṯām', 'H853', 'HTo/Sp3mp', 'a ellas'],
      ['אֱלֹהִ֖ים', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios'],
      [
        'בִּרְקִ֣יעַ',
        'ברקיע',
        'birqîa‘',
        'H7549',
        'HR/Ncmsc',
        'en la expansión de',
      ],
      [
        'הַשָּׁמָ֑יִם',
        'השמים',
        'haššāmāyim',
        'H8064',
        'HTd/Ncmpa',
        'los cielos',
      ],
      ['לְהָאִ֖יר', 'להאיר', 'ləhā’îr', 'H215', 'HR/Vhc', 'para alumbrar'],
      [
        'עַל־הָאָֽרֶץ׃',
        'על־הארץ',
        '‘al-hā’āreṣ',
        'H776',
        'HR/Td/Ncfsa',
        'sobre la tierra,',
      ],
    ],
  },
  {
    verse: 18,
    rawHebrew:
      'וְלִמְשֹׁל֙ בַּיּ֣וֹם וּבַלַּ֔יְלָה וּֽלֲהַבְדִּ֔יל בֵּ֥ין הָא֖וֹר וּבֵ֥ין הַחֹ֑שֶׁךְ וַיַּ֥רְא אֱלֹהִ֖ים כִּי־טֽוֹב׃',
    tokens: [
      [
        'וְלִמְשֹׁל֙',
        'ולמשל',
        'wəlimšōl',
        'H4910',
        'HC/R/Vqc',
        'y para señorear',
      ],
      ['בַּיּ֣וֹם', 'ביום', 'bayyôm', 'H3117', 'HRd/Ncmsa', 'en el día'],
      [
        'וּבַלַּ֔יְלָה',
        'ובלילה',
        'ûḇallayəlâ',
        'H3915',
        'HC/Rd/Ncmsa',
        'y en la noche,',
      ],
      [
        'וּֽלֲהַבְדִּ֔יל',
        'ולהבדיל',
        'ûləhaḇdîl',
        'H914',
        'HC/R/Vhc',
        'y para separar',
      ],
      ['בֵּ֥ין', 'בין', 'bên', 'H996', 'HR', 'entre'],
      ['הָא֖וֹר', 'האור', 'hā’ôr', 'H216', 'HTd/Ncmsa', 'la luz'],
      ['וּבֵ֥ין', 'ובין', 'ûḇên', 'H996', 'HC/R', 'y entre'],
      ['הַחֹ֑שֶׁךְ', 'החשך', 'haḥōšeḵ', 'H2822', 'HTd/Ncmsa', 'las tinieblas.'],
      ['וַיַּ֥רְא', 'וירא', 'wayyar’', 'H7200', 'HC/Vqw3ms', 'Y vio'],
      ['אֱלֹהִ֖ים', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios'],
      [
        'כִּי־טֽוֹב׃',
        'כי־טוב',
        'kî-ṭôḇ',
        'H2896',
        'HC/Aamsa',
        'que era bueno.',
      ],
    ],
  },
  {
    verse: 19,
    rawHebrew: 'וַֽיְהִי־עֶ֥רֶב וַֽיְהִי־בֹ֖קֶר י֥וֹם רְבִיעִֽי׃',
    tokens: [
      [
        'וַֽיְהִי־עֶ֥רֶב',
        'ויהי־ערב',
        'wayhî-‘ereḇ',
        'H6153',
        'HC/Vqw3ms-Ncmsa',
        'Y fue la tarde',
      ],
      [
        'וַֽיְהִי־בֹ֖קֶר',
        'ויהי־בקר',
        'wayhî-ḇōqer',
        'H1242',
        'HC/Vqw3ms-Ncmsa',
        'y fue la mañana',
      ],
      [
        'י֥וֹם רְבִיעִֽי׃',
        'יום רביעי',
        'yôm rəḇî‘î',
        'H7243',
        'HNcmsa/Aomsa',
        'el día cuarto.',
      ],
    ],
  },
  {
    verse: 20,
    rawHebrew:
      'וַיֹּ֣אמֶר אֱלֹהִ֔ים יִשְׁרְצ֣וּ הַמַּ֔יִם שֶׁ֖רֶץ נֶ֣פֶשׁ חַיָּ֑ה וְעוֹף֙ יְעוֹפֵ֣ף עַל־הָאָ֔רֶץ עַל־פְּנֵ֖י רְקִ֥יעַ הַשָּׁמָֽיִם׃',
    tokens: [
      ['וַיֹּ֣אמֶר', 'ויאמר', 'wayyō’mer', 'H559', 'HC/Vqw3ms', 'Y dijo'],
      ['אֱלֹהִ֔ים', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios:'],
      [
        'יִשְׁרְצ֣וּ',
        'ישרצו',
        'yišrəṣû',
        'H8317',
        'HVqi3mp',
        'Produzcan en abundancia',
      ],
      ['הַמַּ֔יִם', 'המים', 'hammayim', 'H4325', 'HTd/Ncmpa', 'las aguas'],
      [
        'שֶׁ֖רֶץ',
        'שרץ',
        'šereṣ',
        'H8318',
        'HNcmsa',
        'seres vivientes / enjambre',
      ],
      ['נֶ֣פֶשׁ', 'נפש', 'nep̱eš', 'H5315', 'HNcfsa', 'de alma / vida'],
      ['חַיָּ֑ה', 'חיה', 'ḥayyâ', 'H2416', 'HAfsa', 'viviente,'],
      ['וְעוֹף֙', 'ועוף', 'wə‘ôp̱', 'H5775', 'HC/Ncmsa', 'y aves'],
      ['יְעוֹפֵ֣ף', 'יעופף', 'yə‘ôp̱ēp̱', 'H5774', 'HVpi3ms', 'vuelen'],
      [
        'עַל־הָאָ֔רֶץ',
        'על־הארץ',
        '‘al-hā’āreṣ',
        'H776',
        'HR/Td/Ncfsa',
        'sobre la tierra,',
      ],
      [
        'עַל־פְּנֵ֖י',
        'על־פני',
        '‘al-pənê',
        'H6440',
        'HR/Ncbpc',
        'en la abierta',
      ],
      ['רְקִ֥יעַ', 'רקיע', 'rəqîa‘', 'H7549', 'HNcmsc', 'expansión de'],
      [
        'הַשָּׁמָֽיִם׃',
        'השמים',
        'haššāmāyim',
        'H8064',
        'HTd/Ncmpa',
        'los cielos.',
      ],
    ],
  },
  {
    verse: 21,
    rawHebrew:
      'וַיִּבְרָ֣א אֱלֹהִ֔ים אֶת־הַתַּנִּינִ֖ם הַגְּדֹלִ֑ים וְאֵ֣ת כָּל־נֶ֣פֶשׁ הַֽחַיָּ֣ה ׀ הָֽרֹמֶ֡שֶׂת אֲשֶׁר֩ שָׁרְצ֨וּ הַמַּ֜יִם לְמִֽינֵהֶ֗ם וְאֵ֨ת כָּל־ע֤וֹף כָּנָף֙ לְמִינֵ֔הוּ וַיַּ֥רְא אֱלֹהִ֖ים כִּי־טֽוֹב׃',
    tokens: [
      ['וַיִּבְרָ֣א', 'ויברא', 'wayyiḇrā’', 'H1254', 'HC/Vqw3ms', 'Y creó'],
      ['אֱלֹהִ֔ים', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios'],
      [
        'אֶת־הַתַּנִּינִ֖ם',
        'את־התנינם',
        '’eṯ-hattannînîm',
        'H8577',
        'HTo/Td/Ncmpa',
        'los grandes monstruos marinos,',
      ],
      [
        'הַגְּדֹלִ֑ים',
        'הגדלים',
        'haggəḏōlîm',
        'H1419',
        'HTd/Aampa',
        'grandes,',
      ],
      ['וְאֵ֣ת', 'ואת', 'wə’ēṯ', 'H853', 'HC/To', 'y todo'],
      ['כָּל־נֶ֣פֶשׁ', 'כל־נפש', 'kāl-nep̱eš', 'H5315', 'HNcmsc/Ncfsa', 'ser'],
      ['הַֽחַיָּ֣ה', 'החיה', 'haḥayyâ', 'H2416', 'HTd/Afsa', 'viviente'],
      [
        'הָֽרֹמֶ֡שֶׂת',
        'הרמשת',
        'hārōmeśeṯ',
        'H7430',
        'HTd/Vqrfsa',
        'que se mueve,',
      ],
      ['אֲשֶׁר֩', 'אשר', '’ăšer', 'H834', 'HTr', 'que'],
      [
        'שָׁרְצ֨וּ',
        'שרצו',
        'šārəṣû',
        'H8317',
        'HVqp3cp',
        'produjeron en abundancia',
      ],
      ['הַמַּ֜יִם', 'המים', 'hammayim', 'H4325', 'HTd/Ncmpa', 'las aguas'],
      [
        'לְמִֽינֵהֶ֗ם',
        'למינהם',
        'ləmînēhem',
        'H4327',
        'HR/Ncmsc/Sp3mp',
        'según su especie,',
      ],
      ['וְאֵ֨ת', 'ואת', 'wə’ēṯ', 'H853', 'HC/To', 'y toda'],
      ['כָּל־ע֤וֹף', 'כל־עוף', 'kāl-‘ôp̱', 'H5775', 'HNcmsc/Ncmsa', 'ave'],
      ['כָּנָף֙', 'כנף', 'kānāp̱', 'H3671', 'HNcfsa', 'alada'],
      [
        'לְמִינֵ֔הוּ',
        'למינהו',
        'ləmînēhû',
        'H4327',
        'HR/Ncmsc/Sp3ms',
        'según su especie.',
      ],
      ['וַיַּ֥רְא', 'וירא', 'wayyar’', 'H7200', 'HC/Vqw3ms', 'Y vio'],
      ['אֱלֹהִ֖ים', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios'],
      [
        'כִּי־טֽוֹב׃',
        'כי־טוב',
        'kî-ṭôḇ',
        'H2896',
        'HC/Aamsa',
        'que era bueno.',
      ],
    ],
  },
  {
    verse: 22,
    rawHebrew:
      'וַיְבָ֧רֶךְ אֹתָ֛ם אֱלֹהִ֖ים לֵאמֹ֑ר פְּר֣וּ וּרְב֗וּ וּמִלְא֤וּ אֶת־הַמַּ֙יִם֙ בַּיַּמִּ֔ים וְהָע֖וֹף יִ֥רֶב בָּאָֽרֶץ׃',
    tokens: [
      [
        'וַיְבָ֧רֶךְ',
        'ויברך',
        'wayḇāreḵ',
        'H1288',
        'HC/Vpw3ms',
        'Y los bendijo',
      ],
      ['אֹתָ֛ם', 'אתם', '’ōṯām', 'H853', 'HTo/Sp3mp', 'a ellos'],
      ['אֱלֹהִ֖ים', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios,'],
      ['לֵאמֹ֑ר', 'לאמר', 'lē’mōr', 'H559', 'HR/Vqc', 'diciendo:'],
      ['פְּר֣וּ', 'פרו', 'pərû', 'H6509', 'HVqv2mp', 'Fructificad'],
      ['וּרְב֗וּ', 'ורבו', 'ûrḇû', 'H7235', 'HC/Vqv2mp', 'y multiplicaos,'],
      ['וּמִלְא֤וּ', 'ומלאו', 'ûmil’û', 'H4390', 'HC/Vqv2mp', 'y llenad'],
      [
        'אֶת־הַמַּ֙יִם֙',
        'את־המים',
        '’eṯ-hammayim',
        'H4325',
        'HTo/Td/Ncmpa',
        'las aguas',
      ],
      [
        'בַּיַּמִּ֔ים',
        'בימים',
        'bayyammîm',
        'H3220',
        'HRd/Ncmpa',
        'en los mares,',
      ],
      ['וְהָע֖וֹף', 'והעוף', 'wəhā‘ôp̱', 'H5775', 'HC/Td/Ncmsa', 'y las aves'],
      ['יִ֥רֶב', 'ירב', 'yireḇ', 'H7235', 'HVqj3ms', 'se multipliquen'],
      ['בָּאָֽרֶץ׃', 'בארץ', 'bā’āreṣ', 'H776', 'HRd/Ncfsa', 'en la tierra.'],
    ],
  },
  {
    verse: 23,
    rawHebrew: 'וַֽיְהִי־עֶ֥רֶב וַֽיְהִי־בֹ֖קֶר י֥וֹם חֲמִישִֽׁי׃',
    tokens: [
      [
        'וַֽיְהִי־עֶ֥רֶב',
        'ויהי־ערב',
        'wayhî-‘ereḇ',
        'H6153',
        'HC/Vqw3ms-Ncmsa',
        'Y fue la tarde',
      ],
      [
        'וַֽיְהִי־בֹ֖קֶר',
        'ויהי־בקר',
        'wayhî-ḇōqer',
        'H1242',
        'HC/Vqw3ms-Ncmsa',
        'y fue la mañana',
      ],
      [
        'י֥וֹם חֲמִישִֽׁי׃',
        'יום חמישי',
        'yôm ḥămîšî',
        'H2549',
        'HNcmsa/Aomsa',
        'el día quinto.',
      ],
    ],
  },
  {
    verse: 24,
    rawHebrew:
      'וַיֹּ֣אמֶר אֱלֹהִ֗ים תּוֹצֵ֨א הָאָ֜רֶץ נֶ֤פֶשׁ חַיָּה֙ לְמִינָ֔הּ בְּהֵמָ֥ה וָרֶ֛מֶשׂ וְחַֽיְתוֹ־אֶ֖רֶץ לְמִינָ֑הּ וַֽיְהִי־כֵֽן׃',
    tokens: [
      ['וַיֹּ֣אמֶר', 'ויאמר', 'wayyō’mer', 'H559', 'HC/Vqw3ms', 'Y dijo'],
      ['אֱלֹהִ֗ים', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios:'],
      ['תּוֹצֵ֨א', 'תוצא', 'tôṣē’', 'H3318', 'HVhj3fs', 'Produzca'],
      ['הָאָ֜רֶץ', 'הארץ', 'hā’āreṣ', 'H776', 'HTd/Ncfsa', 'la tierra'],
      ['נֶ֤פֶשׁ', 'נפש', 'nep̱eš', 'H5315', 'HNcfsa', 'seres'],
      ['חַיָּה֙', 'חיה', 'ḥayyâ', 'H2416', 'HAfsa', 'vivientes'],
      [
        'לְמִינָ֔הּ',
        'למינה',
        'ləmînāh',
        'H4327',
        'HR/Ncmsc/Sp3fs',
        'según su especie:',
      ],
      ['בְּהֵמָ֥ה', 'בהמה', 'bəhēmâ', 'H929', 'HNcfsa', 'bestias,'],
      [
        'וָרֶ֛מֶשׂ',
        'ורמש',
        'wāremeś',
        'H7431',
        'HC/Ncmsa',
        'reptiles / animales que se arrastran,',
      ],
      [
        'וְחַֽיְתוֹ־אֶ֖רֶץ',
        'וחיתו־ארץ',
        'wəḥaytô-’ereṣ',
        'H2416',
        'HC/Ncfsc-Ncfsa',
        'y animales de la tierra',
      ],
      [
        'לְמִינָ֑הּ',
        'למינה',
        'ləmînāh',
        'H4327',
        'HR/Ncmsc/Sp3fs',
        'según su especie.',
      ],
      [
        'וַֽיְהִי־כֵֽן׃',
        'ויהי־כן',
        'wayhî-ḵēn',
        'H3651',
        'HC/Vqw3ms-D',
        'Y fue así.',
      ],
    ],
  },
  {
    verse: 25,
    rawHebrew:
      'וַיַּ֣עַשׂ אֱלֹהִים֩ אֶת־חַיַּ֨ת הָאָ֜רֶץ לְמִינָ֗הּ וְאֶת־הַבְּהֵמָה֙ לְמִינָ֔הּ וְאֵ֛ת כָּל־רֶ֥מֶשׂ הָֽאֲדָמָ֖ה לְמִינֵ֑הוּ וַיַּ֥רְא אֱלֹהִ֖ים כִּי־טֽוֹב׃',
    tokens: [
      ['וַיַּ֣עַשׂ', 'ויעש', 'wayya‘aś', 'H6213', 'HC/Vqw3ms', 'E hizo'],
      ['אֱלֹהִים֩', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios'],
      [
        'אֶת־חַיַּ֨ת',
        'את־חית',
        '’eṯ-ḥayyaṯ',
        'H2416',
        'HTo/Ncfsc',
        'los animales de',
      ],
      ['הָאָ֜רֶץ', 'הארץ', 'hā’āreṣ', 'H776', 'HTd/Ncfsa', 'la tierra'],
      [
        'לְמִינָ֗הּ',
        'למינה',
        'ləmînāh',
        'H4327',
        'HR/Ncmsc/Sp3fs',
        'según su especie,',
      ],
      [
        'וְאֶת־הַבְּהֵמָה֙',
        'ואת־הבהמה',
        'wə’eṯ-habbəhēmâ',
        'H929',
        'HC/To/Td/Ncfsa',
        'y el ganado',
      ],
      [
        'לְמִינָ֔הּ',
        'למינה',
        'ləmînāh',
        'H4327',
        'HR/Ncmsc/Sp3fs',
        'según su especie,',
      ],
      ['וְאֵ֛ת', 'ואת', 'wə’ēṯ', 'H853', 'HC/To', 'y todo'],
      [
        'כָּל־רֶ֥מֶשׂ',
        'כל־רמש',
        'kāl-remeś',
        'H7431',
        'HNcmsc/Ncmsa',
        'animal que se arrastra sobre',
      ],
      ['הָֽאֲדָמָ֖ה', 'האדמה', 'hā’ăḏāmâ', 'H127', 'HTd/Ncfsa', 'la tierra'],
      [
        'לְמִינֵ֑הוּ',
        'למינהו',
        'ləmînēhû',
        'H4327',
        'HR/Ncmsc/Sp3ms',
        'según su especie.',
      ],
      ['וַיַּ֥רְא', 'וירא', 'wayyar’', 'H7200', 'HC/Vqw3ms', 'Y vio'],
      ['אֱלֹהִ֖ים', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios'],
      [
        'כִּי־טֽוֹב׃',
        'כי־טוב',
        'kî-ṭôḇ',
        'H2896',
        'HC/Aamsa',
        'que era bueno.',
      ],
    ],
  },
  {
    verse: 26,
    rawHebrew:
      'וַיֹּ֣אמֶר אֱלֹהִ֔ים נַֽעֲשֶׂ֥ה אָדָ֛ם בְּצַלְמֵ֖נוּ כִּדְמוּתֵ֑נוּ וְיִרְדּוּ֩ בִדְגַ֨ת הַיָּ֜ם וּבְע֣וֹף הַשָּׁמַ֗יִם וּבַבְּהֵמָה֙ וּבְכָל־הָאָ֔רֶץ וּבְכָל־הָרֶ֖מֶשׂ הָֽרֹמֵ֥שׂ עַל־הָאָֽרֶץ׃',
    tokens: [
      ['וַיֹּ֣אמֶר', 'ויאמר', 'wayyō’mer', 'H559', 'HC/Vqw3ms', 'Y dijo'],
      ['אֱלֹהִ֔ים', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios:'],
      ['נַֽעֲשֶׂ֥ה', 'נעשה', 'na‘ăśeh', 'H6213', 'HVqh1cp', 'Hagamos'],
      ['אָדָ֛ם', 'אדם', '’āḏām', 'H120', 'HNcmsa', 'al hombre'],
      [
        'בְּצַלְמֵ֖נוּ',
        'בצלמנו',
        'bəṣalmēnû',
        'H6754',
        'HR/Ncmsc/Sp1cp',
        'a nuestra imagen,',
      ],
      [
        'כִּדְמוּתֵ֑נוּ',
        'כדמותנו',
        'kiḏmûṯēnû',
        'H1823',
        'HR/Ncfsc/Sp1cp',
        'conforme a nuestra semejanza;',
      ],
      ['וְיִרְדּוּ֩', 'וירדו', 'wəyirddû', 'H7287', 'HC/Vqj3mp', 'y señoreen'],
      ['בִדְגַ֨ת', 'בדגת', 'ḇiḏgaṯ', 'H1710', 'HR/Ncfsc', 'en los peces de'],
      ['הַיָּ֜ם', 'הים', 'hayyām', 'H3220', 'HTd/Ncmsa', 'el mar,'],
      [
        'וּבְע֣וֹף',
        'ובעוף',
        'ûḇə‘ôp̱',
        'H5775',
        'HC/R/Ncmsc',
        'y en las aves de',
      ],
      [
        'הַשָּׁמַ֗יִם',
        'השמים',
        'haššāmayim',
        'H8064',
        'HTd/Ncmpa',
        'los cielos,',
      ],
      [
        'וּבַבְּהֵמָה֙',
        'ובבהמה',
        'ûḇabbəhēmâ',
        'H929',
        'HC/Rd/Ncfsa',
        'y en las bestias,',
      ],
      [
        'וּבְכָל־הָאָ֔רֶץ',
        'ובכל־הארץ',
        'ûḇəḵāl-hā’āreṣ',
        'H776',
        'HC/R/Ncmsc/Td/Ncfsa',
        'y en toda la tierra,',
      ],
      [
        'וּבְכָל־הָרֶ֖מֶשׂ',
        'ובכל־הרמש',
        'ûḇəḵāl-hāremeś',
        'H7431',
        'HC/R/Ncmsc/Td/Ncmsa',
        'y en todo animal',
      ],
      [
        'הָֽרֹמֵ֥שׂ',
        'הרמש',
        'hārōmēś',
        'H7430',
        'HTd/Vqrmsa',
        'que se arrastra',
      ],
      [
        'עַל־הָאָֽרֶץ׃',
        'על־הארץ',
        '‘al-hā’āreṣ',
        'H776',
        'HR/Td/Ncfsa',
        'sobre la tierra.',
      ],
    ],
  },
  {
    verse: 27,
    rawHebrew:
      'וַיִּבְרָ֨א אֱלֹהִ֤ים ׀ אֶת־הָֽאָדָם֙ בְּצַלְמ֔וֹ בְּצֶ֥לֶם אֱלֹהִ֖ים בָּרָ֣א אֹת֑וֹ זָכָ֥ר וּנְקֵבָ֖ה בָּרָ֥א אֹתָֽם׃',
    tokens: [
      ['וַיִּבְרָ֨א', 'ויברא', 'wayyiḇrā’', 'H1254', 'HC/Vqw3ms', 'Y creó'],
      ['אֱלֹהִ֤ים', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios'],
      [
        'אֶת־הָֽאָדָם֙',
        'את־האדם',
        '’eṯ-hā’āḏām',
        'H120',
        'HTo/Td/Ncmsa',
        'al hombre',
      ],
      [
        'בְּצַלְמ֔וֹ',
        'בצלמו',
        'bəṣalmô',
        'H6754',
        'HR/Ncmsc/Sp3ms',
        'a su imagen,',
      ],
      ['בְּצֶ֥לֶם', 'בצלם', 'bəṣelem', 'H6754', 'HR/Ncmsc', 'a imagen de'],
      ['אֱלֹהִ֖ים', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios'],
      ['בָּרָ֣א', 'ברא', 'bārā’', 'H1254', 'HVqp3ms', 'lo creó;'],
      ['אֹת֑וֹ', 'אתו', '’ōṯô', 'H853', 'HTo/Sp3ms', 'a él,'],
      ['זָכָ֥ר', 'זכר', 'zāḵār', 'H2145', 'HNcmsa', 'varón'],
      ['וּנְקֵבָ֖ה', 'ונקבה', 'ûnəqēḇâ', 'H5347', 'HC/Ncfsa', 'y hembra'],
      ['בָּרָ֥א', 'ברא', 'bārā’', 'H1254', 'HVqp3ms', 'los creó'],
      ['אֹתָֽם׃', 'אתם', '’ōṯām', 'H853', 'HTo/Sp3mp', 'a ellos.'],
    ],
  },
  {
    verse: 28,
    rawHebrew:
      'וַיְבָ֣רֶךְ אֹתָם֮ אֱלֹהִים֒ וַיֹּ֨אמֶר לָהֶ֜ם אֱלֹהִ֗ים פְּר֥וּ וּרְב֛וּ וּמִלְא֥וּ אֶת־הָאָ֖רֶץ וְכִבְשֻׁ֑הָ וּרְד֞וּ בִּדְגַ֤ת הַיָּם֙ וּבְע֣וֹף הַשָּׁמַ֔יִם וּבְכָל־חַיָּ֖ה הָֽרֹמֶ֥שֶׂת עַל־הָאָֽרֶץ׃',
    tokens: [
      [
        'וַיְבָ֣רֶךְ',
        'ויברך',
        'wayḇāreḵ',
        'H1288',
        'HC/Vpw3ms',
        'Y los bendijo',
      ],
      ['אֹתָם֮', 'אתם', '’ōṯām', 'H853', 'HTo/Sp3mp', 'Dios,'],
      ['אֱלֹהִים֒', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'y les dijo'],
      ['וַיֹּ֨אמֶר', 'ויאמר', 'wayyō’mer', 'H559', 'HC/Vqw3ms', 'Dios:'],
      ['לָהֶ֜ם', 'להם', 'lāhem', 'H3807', 'HR/Sp3mp', 'a ellos,'],
      ['אֱלֹהִ֗ים', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios:'],
      ['פְּר֥וּ', 'פרו', 'pərû', 'H6509', 'HVqv2mp', 'Fructificad'],
      ['וּרְב֛וּ', 'ורבו', 'ûrḇû', 'H7235', 'HC/Vqv2mp', 'y multiplicaos;'],
      ['וּמִלְא֥וּ', 'ומלאו', 'ûmil’û', 'H4390', 'HC/Vqv2mp', 'llenad'],
      [
        'אֶת־הָאָ֖רֶץ',
        'את־הארץ',
        '’eṯ-hā’āreṣ',
        'H776',
        'HTo/Td/Ncfsa',
        'la tierra',
      ],
      [
        'וְכִבְשֻׁ֑הָ',
        'וכבשה',
        'wəḵiḇšuhā',
        'H3533',
        'HC/Vqv2mp/Sp3fs',
        'y sojuzgadla,',
      ],
      ['וּרְד֞וּ', 'ורדו', 'ûrədû', 'H7287', 'HC/Vqv2mp', 'y señoread'],
      ['בִּדְגַ֤ת', 'בדגת', 'biḏgaṯ', 'H1710', 'HR/Ncfsc', 'en los peces de'],
      ['הַיָּם֙', 'הים', 'hayyām', 'H3220', 'HTd/Ncmsa', 'el mar,'],
      [
        'וּבְע֣וֹף',
        'ובעוף',
        'ûḇə‘ôp̱',
        'H5775',
        'HC/R/Ncmsc',
        'y en las aves de',
      ],
      [
        'הַשָּׁמַ֔יִם',
        'השמים',
        'haššāmayim',
        'H8064',
        'HTd/Ncmpa',
        'los cielos,',
      ],
      [
        'וּבְכָל־חַיָּ֖ה',
        'ובכל־חיה',
        'ûḇəḵāl-ḥayyâ',
        'H2416',
        'HC/R/Ncmsc/Ncfsa',
        'y en todas las bestias',
      ],
      [
        'הָֽרֹמֶ֥שֶׂת',
        'הרמשת',
        'hārōmeśeṯ',
        'H7430',
        'HTd/Vqrfsa',
        'que se mueven',
      ],
      [
        'עַל־הָאָֽרֶץ׃',
        'על־הארץ',
        '‘al-hā’āreṣ',
        'H776',
        'HR/Td/Ncfsa',
        'sobre la tierra.',
      ],
    ],
  },
  {
    verse: 29,
    rawHebrew:
      'וַיֹּ֣אמֶר אֱלֹהִ֗ים הִנֵּה֩ נָתַ֨תִּי לָכֶ֜ם אֶת־כָּל־עֵ֣שֶׂב ׀ זֹרֵ֣עַ זֶ֗רַע אֲשֶׁר֙ עַל־פְּנֵ֣י כָל־הָאָ֔רֶץ וְאֶת־כָּל־הָעֵ֛ץ אֲשֶׁר־בּ֥וֹ פְרִי־עֵ֖ץ זֹרֵ֣עַ זָ֑רַע לָכֶ֥ם יִֽהְיֶ֖ה לְאָכְלָֽה׃',
    tokens: [
      ['וַיֹּ֣אמֶר', 'ויאמר', 'wayyō’mer', 'H559', 'HC/Vqw3ms', 'Y dijo'],
      ['אֱלֹהִ֗ים', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios:'],
      ['הִנֵּה֩', 'הנה', 'hinnēh', 'H2009', 'HTm', 'He aquí'],
      ['נָתַ֨תִּי', 'נתתי', 'nāṯattî', 'H5414', 'HVqp1cs', 'que os he dado'],
      ['לָכֶ֜ם', 'לכם', 'lāḵem', 'H3807', 'HR/Sp2mp', 'a vosotros'],
      [
        'אֶת־כָּל־עֵ֣שֶׂב',
        'את־כל־עשב',
        '’eṯ-kāl-‘ēśeḇ',
        'H6212',
        'HTo/Ncmsc/Ncmsa',
        'toda planta',
      ],
      ['זֹרֵ֣עַ', 'זרע', 'zōrēa‘', 'H2232', 'HVqrmsa', 'que da'],
      ['זֶ֗רַע', 'זרע', 'zera‘', 'H2233', 'HNcmsa', 'semilla,'],
      ['אֲשֶׁר֙', 'אשר', '’ăšer', 'H834', 'HTr', 'que [está]'],
      [
        'עַל־פְּנֵ֣י',
        'על־פני',
        '‘al-pənê',
        'H6440',
        'HR/Ncbpc',
        'sobre la faz de',
      ],
      [
        'כָל־הָאָ֔רֶץ',
        'כל־הארץ',
        'ḵāl-hā’āreṣ',
        'H776',
        'HNcmsc/Td/Ncfsa',
        'toda la tierra,',
      ],
      [
        'וְאֶת־כָּל־הָעֵ֛ץ',
        'ואת־כל־העץ',
        'wə’eṯ-kāl-hā‘ēṣ',
        'H6086',
        'HC/To/Ncmsc/Td/Ncmsa',
        'y todo árbol',
      ],
      [
        'אֲשֶׁר־בּ֥וֹ',
        'אשר־בו',
        '’ăšer-bô',
        'H834',
        'HTr-R/Sp3ms',
        'en que hay',
      ],
      [
        'פְרִי־עֵ֖ץ',
        'פרי־עץ',
        'pərî-‘ēṣ',
        'H6529',
        'HNcmsc/Ncmsa',
        'fruto de árbol',
      ],
      ['זֹרֵ֣עַ', 'זרע', 'zōrēa‘', 'H2232', 'HVqrmsa', 'que da'],
      ['זָ֑רַע', 'זרע', 'zāra‘', 'H2233', 'HNcmsa', 'semilla;'],
      ['לָכֶ֥ם', 'לכם', 'lāḵem', 'H3807', 'HR/Sp2mp', 'os'],
      ['יִֽהְיֶ֖ה', 'יהיה', 'yihyeh', 'H1961', 'HVqi3ms', 'será'],
      ['לְאָכְלָֽה׃', 'לאכלה', 'lə’āḵəlâ', 'H402', 'HR/Ncfsa', 'para comer.'],
    ],
  },
  {
    verse: 30,
    rawHebrew:
      'וּֽלְכָל־חַיַּ֣ת הָ֠אָרֶץ וּלְכָל־ע֨וֹף הַשָּׁמַ֜יִם וּלְכֹ֣ל ׀ רוֹמֵ֣שׂ עַל־הָאָ֗רֶץ אֲשֶׁר־בּוֹ֙ נֶ֣פֶשׁ חַיָּ֔ה אֶת־כָּל־יֶ֥רֶק עֵ֖שֶׂב לְאָכְלָ֑ה וַֽיְהִי־כֵֽן׃',
    tokens: [
      [
        'וּֽלְכָל־חַיַּ֣ת',
        'ולכל־חית',
        'ûləḵāl-ḥayyaṯ',
        'H2416',
        'HC/R/Ncmsc/Ncfsc',
        'Y a toda bestia de',
      ],
      ['הָ֠אָרֶץ', 'הארץ', 'hā’āreṣ', 'H776', 'HTd/Ncfsa', 'la tierra,'],
      [
        'וּלְכָל־ע֨וֹף',
        'ולכל־עוף',
        'ûləḵāl-‘ôp̱',
        'H5775',
        'HC/R/Ncmsc/Ncmsa',
        'y a todas las aves de',
      ],
      [
        'הַשָּׁמַ֜יִם',
        'השמים',
        'haššāmayim',
        'H8064',
        'HTd/Ncmpa',
        'los cielos,',
      ],
      ['וּלְכֹ֣ל', 'ולכל', 'ûləḵōl', 'H3605', 'HC/R/Ncmsc', 'y a todo'],
      ['רוֹמֵ֣שׂ', 'רומש', 'rômēś', 'H7430', 'HVqrmsa', 'lo que se arrastra'],
      [
        'עַל־הָאָ֗רֶץ',
        'על־הארץ',
        '‘al-hā’āreṣ',
        'H776',
        'HR/Td/Ncfsa',
        'sobre la tierra,',
      ],
      [
        'אֲשֶׁר־בּוֹ֙',
        'אשר־בו',
        '’ăšer-bô',
        'H834',
        'HTr-R/Sp3ms',
        'en que hay',
      ],
      ['נֶ֣פֶשׁ', 'נפש', 'nep̱eš', 'H5315', 'HNcfsa', 'aliento de'],
      ['חַיָּ֔ה', 'חיה', 'ḥayyâ', 'H2416', 'HAfsa', 'vida,'],
      [
        'אֶת־כָּל־יֶ֥רֶק',
        'את־כל־ירק',
        '’eṯ-kāl-yereq',
        'H3418',
        'HTo/Ncmsc/Ncmsc',
        'toda planta verde',
      ],
      ['עֵ֖שֶׂב', 'עשב', '‘ēśeḇ', 'H6212', 'HNcmsa', 'les será'],
      ['לְאָכְלָ֑ה', 'לאכלה', 'lə’āḵəlâ', 'H402', 'HR/Ncfsa', 'para comer.'],
      [
        'וַֽיְהִי־כֵֽן׃',
        'ויהי־כן',
        'wayhî-ḵēn',
        'H3651',
        'HC/Vqw3ms-D',
        'Y fue así.',
      ],
    ],
  },
  {
    verse: 31,
    rawHebrew:
      'וַיַּ֤רְא אֱלֹהִים֙ אֶת־כָּל־אֲשֶׁ֣ר עָשָׂ֔ה וְהִנֵּה־ט֖וֹב מְאֹ֑ד וַֽיְהִי־עֶ֥רֶב וַֽיְהִי־בֹ֖קֶר י֥וֹם הַשִּׁשִּֽׁי׃',
    tokens: [
      ['וַיַּ֤רְא', 'וירא', 'wayyar’', 'H7200', 'HC/Vqw3ms', 'Y vio'],
      ['אֱלֹהִים֙', 'אלהים', '’ĕlōhîm', 'H430', 'HNcmpa', 'Dios'],
      [
        'אֶת־כָּל־אֲשֶׁ֣ר',
        'את־כל־אשר',
        '’eṯ-kāl-’ăšer',
        'H834',
        'HTo/Ncmsc/Tr',
        'todo lo que',
      ],
      ['עָשָׂ֔ה', 'עשה', '‘āśâ', 'H6213', 'HVqp3ms', 'había hecho,'],
      [
        'וְהִנֵּה־ט֖וֹב',
        'והנה־טוב',
        'wəhinnēh-ṭôḇ',
        'H2896',
        'HC/Tm-Aamsa',
        'y he aquí [que era] bueno',
      ],
      ['מְאֹ֑ד', 'מאד', 'mə’ōḏ', 'H3966', 'HD', 'en gran manera.'],
      [
        'וַֽיְהִי־עֶ֥רֶב',
        'ויהי־ערב',
        'wayhî-‘ereḇ',
        'H6153',
        'HC/Vqw3ms-Ncmsa',
        'Y fue la tarde',
      ],
      [
        'וַֽיְהִי־בֹ֖קֶר',
        'ויהי־בקר',
        'wayhî-ḇōqer',
        'H1242',
        'HC/Vqw3ms-Ncmsa',
        'y fue la mañana',
      ],
      [
        'י֥וֹם הַשִּׁשִּֽׁי׃',
        'יום הששי',
        'yôm haššiššî',
        'H8345',
        'HNcmsa/Td/Aomsa',
        'el día sexto.',
      ],
    ],
  },
];

// 2. Léxicos Strong integrales de Génesis 1
const LEXICON_ENTRIES: LexiconEntryDef[] = [
  {
    strongCode: 'H7225',
    language: 'Hebrew',
    lemma: 'רֵאשִׁית',
    transliteration: 'rē’šîṯ',
    ipa: '/reːˈʃiːt/',
    partOfSpeech: 'Sustantivo femenino',
    shortDefinition: 'Principio, comienzo, primicias, lo principal.',
    extendedDefinition:
      'BDB / Gesenius: 1. Punto de partida temporal o procesal (Gn 1:1, Pr 8:22). 2. Lo mejor o más selecto de una cosecha o posesión (Éx 23:19). 3. Primacía en rango o dignidad.',
  },
  {
    strongCode: 'H1254',
    language: 'Hebrew',
    lemma: 'בָּרָא',
    transliteration: 'bārā’',
    ipa: '/baːˈraːʔ/',
    partOfSpeech: 'Verbo (Tronco Qal)',
    shortDefinition: 'Crear, dar origen de la nada, moldear soberanamente.',
    extendedDefinition:
      'BDB: Verbo reservado exclusivamente a la actividad creadora de Dios en la Biblia Hebrea. Nunca tiene como sujeto a un ser humano ni menciona materia preexistente. Expresa la originación absoluta y soberana por parte de Yahvé.',
  },
  {
    strongCode: 'H430',
    language: 'Hebrew',
    lemma: 'אֱלֹהִים',
    transliteration: '’ĕlōhîm',
    ipa: '/ʔĕloːˈhiːm/',
    partOfSpeech: 'Sustantivo masculino plural',
    shortDefinition: 'Dios, el Creador Supremo, la Deidad Única.',
    extendedDefinition:
      'BDB / Gesenius: Plural de majestad o plenitud de poder divino (pluralis majestatis / excellentiae). Cuando se refiere al Dios verdadero de Israel, rige invariablemente verbos y adjetivos en singular (ej. bara en Gn 1:1), enfatizando su unidad intrínseca y su infinita soberanía.',
  },
  {
    strongCode: 'H8064',
    language: 'Hebrew',
    lemma: 'שָׁמַיִם',
    transliteration: 'šāmayim',
    ipa: '/ʃaːˈmajim/',
    partOfSpeech: 'Sustantivo masculino dual / plural',
    shortDefinition: 'Cielos, bóveda celeste, morada de la gloria de Dios.',
    extendedDefinition:
      'BDB: 1. El firmamento visible y la atmósfera cósmica. 2. Las altas regiones de los cuerpos celestes. 3. La dimensión trascendente y trono de la presencia divina.',
  },
  {
    strongCode: 'H776',
    language: 'Hebrew',
    lemma: 'אֶרֶץ',
    transliteration: '’ereṣ',
    ipa: '/ˈʔɛrɛsˤ/',
    partOfSpeech: 'Sustantivo femenino',
    shortDefinition: 'Tierra, suelo, mundo terrenal, territorio habitado.',
    extendedDefinition:
      'BDB: 1. El globo terráqueo en oposición a los cielos (merisma cósmico en Gn 1:1: cielos y tierra = todo el universo). 2. Suelo firme y seco. 3. País o territorio geográfico específico.',
  },
  {
    strongCode: 'H8414',
    language: 'Hebrew',
    lemma: 'תֹּהוּ',
    transliteration: 'tōhû',
    ipa: '/ˈtoːhuː/',
    partOfSpeech: 'Sustantivo masculino',
    shortDefinition: 'Desolación, sin forma, informe, lugar desierto.',
    extendedDefinition:
      'BDB: Estado primordial no configurado ni estructurado previo a los mandatos ordenadores de los Días 1-3. Formulado en el pareado asonante Tohu va-Vohu.',
  },
  {
    strongCode: 'H922',
    language: 'Hebrew',
    lemma: 'בֹּהוּ',
    transliteration: 'bōhû',
    ipa: '/ˈboːhuː/',
    partOfSpeech: 'Sustantivo masculino',
    shortDefinition: 'Vacío, sin habitantes ni contenido.',
    extendedDefinition:
      'BDB: Ausencia de plenitud o habitantes previo a los mandatos de llenado de los Días 4-6. Describe el cosmos antes de ser poblado por lumbreras, criaturas marinas, aves y seres terrestres.',
  },
  {
    strongCode: 'H2822',
    language: 'Hebrew',
    lemma: 'חֹשֶׁךְ',
    transliteration: 'ḥōšek',
    ipa: '/ˈħoːʃɛx/',
    partOfSpeech: 'Sustantivo masculino',
    shortDefinition: 'Tinieblas, oscuridad, ausencia de luz visible.',
    extendedDefinition:
      'BDB: Densas tinieblas primordiales sobre el abismo antes del primer fiat divino (Gn 1:2-3).',
  },
  {
    strongCode: 'H8415',
    language: 'Hebrew',
    lemma: 'תְּהוֹם',
    transliteration: 'təhôm',
    ipa: '/təˈhoːm/',
    partOfSpeech: 'Sustantivo femenino',
    shortDefinition:
      'Abismo, profundidad oceánica primordial, aguas subterráneas.',
    extendedDefinition:
      'BDB: La masa oceánica profunda primordial que cubría la tierra antes de la emergencia del suelo seco.',
  },
  {
    strongCode: 'H7307',
    language: 'Hebrew',
    lemma: 'רוּחַ',
    transliteration: 'rûaḥ',
    ipa: '/ˈruːaħ/',
    partOfSpeech: 'Sustantivo femenino',
    shortDefinition:
      'Espíritu, aliento, viento, presencia vivificante de Dios.',
    extendedDefinition:
      'BDB: 1. Ruaj Elohim: El Espíritu de Dios en acción soberana sobre la faz de las aguas primordiales (Gn 1:2). 2. Aliento de vida y principio vital impartido a las criaturas.',
  },
  {
    strongCode: 'H4325',
    language: 'Hebrew',
    lemma: 'מַיִם',
    transliteration: 'mayim',
    ipa: '/ˈmajim/',
    partOfSpeech: 'Sustantivo masculino dual',
    shortDefinition: 'Aguas, mares, ríos, líquido vivificante.',
    extendedDefinition:
      'BDB: Masa acuática primordial y elementos hidrológicos del orden creado.',
  },
  {
    strongCode: 'H216',
    language: 'Hebrew',
    lemma: 'אוֹר',
    transliteration: '’ôr',
    ipa: '/ʔoːr/',
    partOfSpeech: 'Sustantivo masculino',
    shortDefinition: 'Luz, resplandor, iluminación divina, aurora.',
    extendedDefinition:
      "BDB: La primera entidad llamada a existir por la palabra de Dios (Día 1: 'Hágase la luz'). Representa orden, claridad, vida y la revelación de la gloria divina.",
  },
  {
    strongCode: 'H7549',
    language: 'Hebrew',
    lemma: 'רָקִיעַ',
    transliteration: 'rāqîa‘',
    ipa: '/raːˈqiːaʕ/',
    partOfSpeech: 'Sustantivo masculino',
    shortDefinition: 'Expansión, bóveda celeste, firmamento.',
    extendedDefinition:
      'BDB / Gesenius: Espacio extendido o lámina atmosférica creada en el Día 2 para separar las aguas superiores (humedad, nubes) de las aguas inferiores (océanos, mares).',
  },
  {
    strongCode: 'H3117',
    language: 'Hebrew',
    lemma: 'יוֹם',
    transliteration: 'yôm',
    ipa: '/joːm/',
    partOfSpeech: 'Sustantivo masculino',
    shortDefinition: 'Día, período diurno de luz, época, jornada.',
    extendedDefinition:
      'BDB: 1. El período diurno en contraste con la noche (Gn 1:5). 2. Ciclo compuesto de tarde y mañana (yom ejad, yom sheni...). 3. Tiempo o período determinado.',
  },
  {
    strongCode: 'H3915',
    language: 'Hebrew',
    lemma: 'לַיְלָה',
    transliteration: 'laylâ',
    ipa: '/ˈlajlaː/',
    partOfSpeech: 'Sustantivo masculino',
    shortDefinition: 'Noche, tiempo de reposo, oscuridad regulada.',
    extendedDefinition:
      'BDB: El espacio de tiempo oscuro designado por Dios y gobernado por la lumbrera menor y las estrellas (Gn 1:5, 16).',
  },
  {
    strongCode: 'H3974',
    language: 'Hebrew',
    lemma: 'מָאוֹר',
    transliteration: 'mā’ôr',
    ipa: '/maːˈʔoːr/',
    partOfSpeech: 'Sustantivo masculino',
    shortDefinition: 'Lumbrera, cuerpo luminoso, astro emisor de luz.',
    extendedDefinition:
      'BDB: Los cuerpos celestes (sol, luna y estrellas) fijados en el firmamento en el Día 4 para regular el calendario, las estaciones y la iluminación de la tierra.',
  },
  {
    strongCode: 'H5775',
    language: 'Hebrew',
    lemma: 'עוֹף',
    transliteration: '‘ôp̱',
    ipa: '/ʕoːf/',
    partOfSpeech: 'Sustantivo masculino colectivo',
    shortDefinition: 'Aves, criaturas aladas voladoras.',
    extendedDefinition:
      'BDB: Todo ser dotado de alas que vuela en la atmósfera y expansión de los cielos (Gn 1:20-22).',
  },
  {
    strongCode: 'H8577',
    language: 'Hebrew',
    lemma: 'תַּנִּין',
    transliteration: 'tannîn',
    ipa: '/tanˈniːn/',
    partOfSpeech: 'Sustantivo masculino',
    shortDefinition: 'Grandes monstruos marinos, cetáceos, reptiles gigantes.',
    extendedDefinition:
      'BDB: Las colosales criaturas marinas creadas en el Día 5 (Gn 1:21), desmitologizadas frente a las leyendas paganas de dragones acuáticos caóticos.',
  },
  {
    strongCode: 'H929',
    language: 'Hebrew',
    lemma: 'בְּהֵמָה',
    transliteration: 'bəhēmâ',
    ipa: '/bəheːˈmaː/',
    partOfSpeech: 'Sustantivo femenino',
    shortDefinition: 'Bestia, ganado, animal cuadrúpedo doméstico.',
    extendedDefinition:
      'BDB: Animales terrestres de gran porte y ganado domesticable creados en el Día 6 (Gn 1:24-25).',
  },
  {
    strongCode: 'H120',
    language: 'Hebrew',
    lemma: 'אָדָם',
    transliteration: '’āḏām',
    ipa: '/ʔaːˈdaːm/',
    partOfSpeech: 'Sustantivo masculino',
    shortDefinition: 'Hombre, ser humano, humanidad, el primer hombre Adán.',
    extendedDefinition:
      'BDB / Gesenius: La raza humana constituida como cumbre de la creación, modelada a imagen de Dios y relacionada etimológicamente con la tierra (Adamah).',
  },
  {
    strongCode: 'H5315',
    language: 'Hebrew',
    lemma: 'נֶפֶשׁ',
    transliteration: 'nepeš',
    ipa: '/ˈnɛfɛʃ/',
    partOfSpeech: 'Sustantivo femenino',
    shortDefinition: 'Alma, ser viviente, vida, criatura animada, persona.',
    extendedDefinition:
      'BDB: 1. Nefesh jayyah: Ser viviente animado con respiración y vitalidad orgánica (Gn 1:20, 24). 2. La vida intrínseca de los animales y del ser humano.',
  },
  {
    strongCode: 'H6754',
    language: 'Hebrew',
    lemma: 'צֶלֶם',
    transliteration: 'ṣelem',
    ipa: '/ˈsˤɛlɛm/',
    partOfSpeech: 'Sustantivo masculino',
    shortDefinition: 'Imagen, representación, semejanza representativa.',
    extendedDefinition:
      'BDB / Gesenius: Imago Dei (Gn 1:26-27). El ser humano constituido como representante y mayordomo soberano de Dios en la tierra, dotado de capacidad moral, racional, relacional y dominio delegado.',
  },
  {
    strongCode: 'H1823',
    language: 'Hebrew',
    lemma: 'דְּמוּת',
    transliteration: 'dəmûṯ',
    ipa: '/dəˈmuːt/',
    partOfSpeech: 'Sustantivo femenino',
    shortDefinition: 'Semejanza, patrón, afinidad de naturaleza y carácter.',
    extendedDefinition:
      'BDB: Término complementario a tselem que enfatiza la correspondencia y reflejo fiel del carácter y los propósitos de Dios en la criatura humana.',
  },
  {
    strongCode: 'H2896',
    language: 'Hebrew',
    lemma: 'טוֹב',
    transliteration: 'ṭôḇ',
    ipa: '/tˤoːv/',
    partOfSpeech: 'Adjetivo masculino',
    shortDefinition: 'Bueno, perfecto, armónico, placentero, provechoso.',
    extendedDefinition:
      "BDB: Declaración evaluativa divina del cosmos: 'Ki-tov' (Porque era bueno) repetida 7 veces en la semana de la Creación, culminando en 'Tov Me'od' (Bueno en gran manera) en Gn 1:31.",
  },
  {
    strongCode: 'H1288',
    language: 'Hebrew',
    lemma: 'בָּרַךְ',
    transliteration: 'bāraḵ',
    ipa: '/baːˈrax/',
    partOfSpeech: 'Verbo (Tronco Piel)',
    shortDefinition: 'Bendecir, impartir fecundidad, prosperar.',
    extendedDefinition:
      'BDB: Acto divino de conferir capacidad reproductiva, vida abundante y prosperidad vital a las criaturas marinas, aves y a la humanidad (Gn 1:22, 28).',
  },
  {
    strongCode: 'H6509',
    language: 'Hebrew',
    lemma: 'פָּרָה',
    transliteration: 'pārâ',
    ipa: '/paːˈraː/',
    partOfSpeech: 'Verbo (Tronco Qal)',
    shortDefinition: 'Fructificar, ser fecundo, dar fruto.',
    extendedDefinition:
      'BDB: Mandato creacional de fecundidad y desarrollo de la vida orgánica sobre la tierra.',
  },
  {
    strongCode: 'H7235',
    language: 'Hebrew',
    lemma: 'רָבָה',
    transliteration: 'rāḇâ',
    ipa: '/raːˈvaː/',
    partOfSpeech: 'Verbo (Tronco Qal)',
    shortDefinition: 'Multiplicar, aumentar en número y plenitud.',
    extendedDefinition:
      'BDB: Crecimiento expansivo de la población de las criaturas creadas para poblar los nichos cósmicos.',
  },
  {
    strongCode: 'H3533',
    language: 'Hebrew',
    lemma: 'כָּבַשׁ',
    transliteration: 'kāḇaš',
    ipa: '/kaːˈvaʃ/',
    partOfSpeech: 'Verbo (Tronco Qal)',
    shortDefinition: 'Sojuzgar, cultivar responsablemente, poner en orden.',
    extendedDefinition:
      'BDB: Mayordomía delegada a la humanidad para gobernar pacíficamente los recursos naturales y desplegar el potencial de la creación.',
  },
  {
    strongCode: 'H7287',
    language: 'Hebrew',
    lemma: 'רָדָה',
    transliteration: 'rādâ',
    ipa: '/raːˈdaː/',
    partOfSpeech: 'Verbo (Tronco Qal)',
    shortDefinition: 'Señorear, gobernar benévolamente, ejercer dominio.',
    extendedDefinition:
      'BDB: Mayordomía vicaria del hombre como virrey de Dios sobre los reinos acuático, aéreo y terrestre.',
  },
  {
    strongCode: 'H7673',
    language: 'Hebrew',
    lemma: 'שָׁבַת',
    transliteration: 'šāḇaṯ',
    ipa: '/ʃaːˈvat/',
    partOfSpeech: 'Verbo (Tronco Qal)',
    shortDefinition:
      'Cesar, reposar, concluir la obra, santificar el descanso.',
    extendedDefinition:
      'BDB: Cesar la labor productiva tras completar plenamente la obra cósmica. Base del Shabat (Día Séptimo, Gn 2:1-3).',
  },
];

// Generar JSON de tokens
const tokensOutput: VerseTokens[] = GENESIS_1_VERSES.map((v) => ({
  chapter: 1,
  verseNumber: v.verse,
  tokens: v.tokens.map((tok, idx) => ({
    wordOrder: idx + 1,
    surfaceText: tok[0],
    consonantsOnly: tok[1],
    transliteration: tok[2],
    strongCode: tok[3],
    morphologyCode: tok[4],
    gloss: tok[5],
  })),
}));

const targetTokensPath = path.join(
  __dirname,
  '..',
  'corpus',
  'morphology',
  'genesis_01_tokens.json',
);
const targetLexiconPath = path.join(
  __dirname,
  '..',
  'corpus',
  'morphology',
  'genesis_01_lexicon.json',
);

fs.writeFileSync(
  targetTokensPath,
  JSON.stringify(tokensOutput, null, 2),
  'utf8',
);
fs.writeFileSync(
  targetLexiconPath,
  JSON.stringify(LEXICON_ENTRIES, null, 2),
  'utf8',
);

const totalTokens = tokensOutput.reduce((acc, v) => acc + v.tokens.length, 0);
console.log(
  `[FullGen1Builder] ✨ Generados con éxito ${tokensOutput.length} versículos de Génesis 1 (${totalTokens} tokens morfológicos totales).`,
);
console.log(
  `[FullGen1Builder] ✨ Generadas ${LEXICON_ENTRIES.length} entradas léxicas Strong completas.`,
);
